// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "2605116008@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Auth/ApplicationWebAuthn": {
            "get": {
                "description": "在注册一个凭证之前，先向服务器获取其WebAuthn的配置如：RPID,Alg ,详见：https://zhuanlan.zhihu.com/p/1966472631474717161",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NotAuth"
                ],
                "summary": "ApplicationWebAuthn-获取server配置项",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/swagger.WebAuthnInfo"
                        }
                    },
                    "400": {
                        "description": "获取失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Auth/GetChallenge": {
            "get": {
                "description": "在 OAuth2.0规范中，首先client端要在server获取一个随机数，server会缓存下来，在第二次正式登录client会附带这个随机数在请求url（state），由server验证这个随机数是否与缓存的一致，用于防重放",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NotAuth"
                ],
                "summary": "OAuth2.0-在服务端获取一个随机数",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/types.Challenge"
                        }
                    },
                    "400": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/swagger.GetChallengeIsFail"
                        }
                    }
                }
            }
        },
        "/Auth/Login": {
            "post": {
                "description": "1.Email，password登录  2.Token登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NotAuth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "jwt",
                        "name": "AccessToken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "jwt",
                        "name": "RefreshToken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/types.LoginInfo"
                        }
                    },
                    "400": {
                        "description": "密码错误",
                        "schema": {
                            "$ref": "#/definitions/swagger.PasswordIsFail"
                        }
                    },
                    "4001": {
                        "description": "token无效",
                        "schema": {
                            "$ref": "#/definitions/swagger.JwtTokenInvalid"
                        }
                    },
                    "4002": {
                        "description": "token过期",
                        "schema": {
                            "$ref": "#/definitions/swagger.JwtTokenExpired"
                        }
                    }
                }
            }
        },
        "/Auth/LoginByWebAuthn": {
            "get": {
                "description": "客户端在url传递state，code， 服务端验证state，并用code向OAuth提供方换取AcessToken和RefreshToken，并返回用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NotAuth"
                ],
                "summary": "OAuth2.0-验证并登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "作用：防重放",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "作用：向OAuth提供商换取token",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/types.LoginInfo"
                        }
                    },
                    "400": {
                        "description": "获取失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Auth/WebAuthnByLogin": {
            "post": {
                "description": "使用WebAuth安全密钥登录，详见：https://zhuanlan.zhihu.com/p/1966472631474717161",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NotAuth"
                ],
                "summary": "ApplicationWebAuthn-获取server配置项",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/types.LoginInfo"
                        }
                    },
                    "400": {
                        "description": "获取失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Consts.Alg": {
            "type": "object",
            "properties": {
                "alg": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "swagger.Config": {
            "type": "object",
            "properties": {
                "attachment": {
                    "description": "认证器证明方式",
                    "type": "string"
                },
                "attestation": {
                    "description": "认证器类型",
                    "type": "string"
                },
                "challengeTTL": {
                    "type": "integer",
                    "format": "int64"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "网站信息",
                    "type": "string"
                },
                "pubKeyCredParams": {
                    "description": "webAuthn服务器配置信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Consts.Alg"
                    }
                },
                "timeOut": {
                    "$ref": "#/definitions/time.Duration"
                },
                "userID": {
                    "description": "注册服务的用户信息",
                    "type": "integer",
                    "format": "int64"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "swagger.GetChallengeIsFail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "获取随机数失败：...."
                }
            }
        },
        "swagger.JwtTokenExpired": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400100
                },
                "message": {
                    "type": "string",
                    "example": "Token Expired"
                }
            }
        },
        "swagger.JwtTokenInvalid": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400101
                },
                "message": {
                    "type": "string",
                    "example": "Token is invalid"
                }
            }
        },
        "swagger.PasswordIsFail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Password is fail"
                }
            }
        },
        "swagger.WebAuthnInfo": {
            "type": "object",
            "properties": {
                "challenge": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/swagger.Config"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000,
                1,
                1000,
                1000000,
                1000000000,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        },
        "types.Auth": {
            "type": "object",
            "properties": {
                "AccessToken": {
                    "type": "string"
                },
                "RefreshToken": {
                    "type": "string"
                }
            }
        },
        "types.Challenge": {
            "type": "object",
            "properties": {
                "challenge": {
                    "type": "string"
                }
            }
        },
        "types.LoginInfo": {
            "type": "object",
            "properties": {
                "auth": {
                    "description": "鉴权信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Auth"
                        }
                    ]
                },
                "avatar": {},
                "nickname": {
                    "description": "用户信息",
                    "type": "string",
                    "example": "Suis"
                },
                "userid": {
                    "type": "integer",
                    "example": 1162667863010451456
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3008",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Note",
	Description:      "Suis",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
